### ISSUE TITLE
GULP steps, 4 and 5 failing

### ISSUE THREAD

**Issue by jccote** [Sitecore/Habitat#142]
The first three gulp setup steps are working, then the XML transforms fail, most but not all.  I've pasted a typical error message here, then shown the whole list of projects with "WORKED!" next to the few that worked.  I'm hoping you'll see a pattern to this.

Unicorn step also failing, added that error at the very bottom:

TYPICAL XML TRANSFORM ERROR:
[23:14:46] { [Error: Command failed: C:\Windows\system32\cmd.exe /s /c ""C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "c:\Projects\habitat\src\Feature\Accounts\code\Sitecore.Feature.Accounts.csproj" "/target:ApplyTransform" /verbosity:normal /toolsversion:14.0 /nologo /maxcpucount /property:Configuration="Debug" /property:WebConfigToTransform="C:\websites\Habitat.local\Website""
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c ""C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe" "c:\\Projects\\habitat\\src\\Feature\\Accounts\\code\\Sitecore.Feature.Accounts.csproj" "/target:ApplyTransform" /verbosity:normal /toolsversion:14.0 /nologo /maxcpucount /property:Configuration="Debug" /property:WebConfigToTransform="C:\\websites\\Habitat.local\\Website""' }
[23:14:46] Build failed!

LIST OF TRANSFORMS with a few that worked:
WORKED!    Applying transform project: src\Project\Common\code\Sitecore.Common.Website.csproj
WORKED!    Applying transform project: src\Project\Habitat\code\Sitecore.Habitat.Website.csproj
[23:33:26] Applying transform project: src\Feature\Accounts\code\Sitecore.Feature.Accounts.csproj
[23:33:28] Applying transform project: src\Feature\faq\code\Sitecore.Feature.FAQ.csproj
[23:33:29] Applying transform project: src\Feature\Demo\code\Sitecore.Feature.Demo.csproj
[23:33:29] Applying transform project: src\Feature\Identity\code\Sitecore.Feature.Identity.csproj
[23:33:30] Applying transform project: src\Feature\Language\code\Sitecore.Feature.Language.csproj
[23:33:31] Applying transform project: src\Feature\Maps\code\Sitecore.Feature.Maps.csproj
[23:33:32] Applying transform project: src\Feature\Media\code\Sitecore.Feature.Media.csproj
[23:33:33] Applying transform project: src\Feature\Metadata\code\Sitecore.Feature.Metadata.csproj
[23:33:35] Applying transform project: src\Feature\Multisite\code\Sitecore.Feature.Multisite.csproj
[23:33:36] Applying transform project: src\Feature\Navigation\code\Sitecore.Feature.Navigation.csproj
[23:33:37] Applying transform project: src\Feature\News\code\Sitecore.Feature.News.csproj
[23:33:38] Applying transform project: src\Feature\PageContent\code\Sitecore.Feature.PageContent.csproj
[23:33:39] Applying transform project: src\Feature\Person\code\Sitecore.Feature.Person.csproj
[23:33:40] Applying transform project: src\Feature\Search\code\Sitecore.Feature.Search.csproj
[23:33:41] Applying transform project: src\Feature\Social\code\Sitecore.Feature.Social.csproj
[23:33:42] Applying transform project: src\Feature\Teasers\code\Sitecore.Feature.Teasers.csproj
WORKED!    Applying transform project: src\Foundation\Accounts\code\Foundation.Accounts.csproj
[23:33:44] Applying transform project: src\Foundation\Alerts\code\Sitecore.Foundation.Alerts.csproj
[23:33:45] Applying transform project: src\Foundation\Assets\code\Sitecore.Foundation.Assets.csproj
[23:33:46] Applying transform project: src\Foundation\Forms\code\Sitecore.Foundation.Forms.csproj
[23:33:47] Applying transform project: src\Foundation\Indexing\code\Sitecore.Foundation.Indexing.csproj
WORKED!    Applying transform project: src\Foundation\Installer\code\Sitecore.Foundation.Installer.csproj
[23:33:49] Applying transform project: src\Foundation\Multisite\code\Sitecore.Foundation.Multisite.csproj
[23:33:50] Applying transform project: src\Foundation\Serialization\code\Sitecore.Foundation.Serialization.csproj
[23:33:51] Applying transform project: src\Foundation\SitecoreExtensions\code\Sitecore.Foundation.SitecoreExtensions.csproj
[23:33:52] Applying transform project: src\Foundation\Theming\code\Sitecore.Foundation.Theming.csproj
WORKED!    Applying transform project: src\Project\Common\code\Sitecore.Common.Website.csproj
WORKED!    Applying transform project: src\Project\Habitat\code\Sitecore.Habitat.Website.csproj
[23:33:55] Applying transform project: src\Project\Demo\code\Sitecore.Demo.Website.csproj
Process terminated with code 0.

UNICORN STEP 5 ERROR:

c:\Projects\habitat\scripts\unicorn.js:78
    if (err !== null) throw err;
                      ^

Error: Command failed: C:\Windows\system32\cmd.exe /s /c "powershell -executionpolicy unrestricted "./Sync.ps1 -secret kl3KGocnbp3L9ncCZYRPwFwiW7jW2UhE02T3GZU6sL5rTCKZzsRyRYLtGzuh8Li -url http://habitat.local/unicorn.aspx -configurations Foundation.Serialization^Foundation.Assets^Foundation.Forms^Foundation.Indexing^Foundation.Multisite^Foundation.SitecoreExtensions^Feature.Accounts^Feature.Demo^Feature.FAQ^Feature.Identity^Feature.Language^Feature.Maps^Feature.Media^Feature.Metadata^Feature.Multisite^Feature.Navigation^Feature.News^Feature.PageContent^Feature.Person^Feature.Search^Feature.Social^Feature.Teasers^Project.Common.Website^Project.Demo.Website^Project.Habitat.Website""
Add-Type : Could not load file or assembly 'file:///C:\Projects\habitat\scripts\Unicorn\MicroCHAP.dll' or one of its
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At C:\Projects\habitat\scripts\Unicorn\Unicorn.psm1:3 char:1
+ Add-Type -Path '.\MicroCHAP.dll'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.AddTypeCommand

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by dashkodo** [comment]
Download latest changes and try again
