### ISSUE TITLE
ERROR: Bad IL format during Unicorn sync of Project.Common.Website

### ISSUE THREAD

**Issue by sansani4** [Sitecore/Habitat#202]
Hello,

I get the following during Unicorn sync:

Project.Common.Website is being synced.
---------------------------------------------

[U] master:/sitecore/system/Languages (64c4f646-a3fa-4205-b98e-4de2c609b60f)
[A] master:/sitecore/system/Languages/da (2403d44d-a04e-4c4f-b00b-5ce8cf531254)
[U] master:/sitecore/templates/Project/Common/Content Types/Teasers/Teaser/__Standard Values (28442a49-f6d9-4efd-865d-9df0b74b512b)
**ERROR: Bad IL format. (System.BadImageFormatException)**
at Sitecore.Data.Database.GetItem(ID itemId) 
at Unicorn.Pipelines.UnicornSyncComplete.SyncedItemPostProcessor.<>c__DisplayClass0_0.b__1(ChangeEntry change) 
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() 
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() 
at System.Linq.Buffer`1..ctor(IEnumerable`1 source) 
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source) 
at Unicorn.Pipelines.UnicornSyncComplete.SyncedItemPostProcessor.Process(UnicornSyncCompletePipelineArgs args) 
at (Object , Object[] ) 
at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) 
at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) 
at Unicorn.SerializationHelper.SyncTree(IConfiguration configuration, Action`1 rootLoadedCallback, IItemData[] roots) 
at Unicorn.ControlPanel.Pipelines.UnicornControlPanelRequest.SyncVerb.Process(IProgressStatus progress, ILogger additionalLogger)

Project.Habitat.Website is being synced
-------------------------------------------

[U] master:/sitecore/system/Modules/Web Forms for Marketers/Habitat/Leave an Email (fbda72a7-7867-455a-b91e-36b2d9d56660)
[U] master:/sitecore/system/Modules/Web Forms for Marketers/Habitat/Leave an Email/Email (1a1d3877-8ee9-4bcc-8392-6804b96ba277)
**ERROR: Bad IL format. (System.BadImageFormatException)**
at Sitecore.Data.Database.GetItem(ID itemId) 
at Unicorn.Pipelines.UnicornSyncComplete.SyncedItemPostProcessor.<>c__DisplayClass0_0.b__1(ChangeEntry change) 
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() 
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() 
at System.Linq.Buffer`1..ctor(IEnumerable`1 source) 
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source) 
at Unicorn.Pipelines.UnicornSyncComplete.SyncedItemPostProcessor.Process(UnicornSyncCompletePipelineArgs args) 
at (Object , Object[] ) 
at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) 
at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) 
at Unicorn.SerializationHelper.SyncTree(IConfiguration configuration, Action`1 rootLoadedCallback, IItemData[] roots) 
at Unicorn.ControlPanel.Pipelines.UnicornControlPanelRequest.SyncVerb.Process(IProgressStatus progress, ILogger additionalLogger)

Best regards,
Sasha

@Eldblom

**Comment by yalahyane** [comment]
Hello Sasha,
Which version of Sitecore are you using?

Thanks.

Yassine

**Comment by sansani4** [comment]
Hi Yassine,

Sitecore 8.2

Thank you,
Sasha

**Comment by yalahyane** [comment]
We didn't merge release/8.2 to master branch yet unfortunately. So for now master will have some issues with 8.2. The merge will be done very soon.

**Comment by sansani4** [comment]
Got it!

Thank you very much for your time, Yassine.

Best regards,
Sasha

**Comment by yalahyane** [comment]
No problem, i'll let you know as soon as it's ready.
Regards,

Yassine
