### ISSUE TITLE
Error creating package in Sitecore

### ISSUE THREAD

**Issue by jeeby** [Sitecore/Habitat#270]
On a Habitat-based site, I'm trying to create a package in Sitecore Package Designer.  I can add all the content without issues, but when I "Generate Zip" it throws the following error:
  
`Package generation failed: Could not find configuration node: databases/database[@id=''].`

More error details in the log:

```
`ManagedPoolThread #5 16:03:35 ERROR Package generation failed: System.InvalidOperationException: Could not find configuration node: databases/database[@id='']
   at Sitecore.Configuration.Factory.GetConfigNode(String xpath, Boolean assert)
   at Sitecore.Configuration.Factory.CreateObject(String configPath, String[] parameters, Boolean assert)
   at Sitecore.Configuration.Factory.GetDatabase(String name, Boolean assert)
   at Sitecore.Configuration.Factory.GetDatabase(String name)
   at Sitecore.Install.Items.ItemSource.InternalPopulate(ISink`1 sink)
   at Sitecore.Install.Framework.BaseSource`1.Populate(ISink`1 sink)
   at Sitecore.Install.PackageProject.InternalPopulate(ISink`1 sink)
   at Sitecore.Install.Framework.BaseSource`1.Populate(ISink`1 sink)
   at Sitecore.Install.Utils.EntrySorter.Populate(ISink`1 sink)
   at Sitecore.Install.PackageGenerator.GeneratePackage(PackageProject solution, ISink`1 writer)
   at Sitecore.Install.PackageGenerator.GeneratePackage(String solutionFile, String packageFile, IProcessingContext context)
   at Sitecore.Shell.Applications.Install.Dialogs.BuildPackage.AsyncHelper.Generate()
ManagedPoolThread #5 16:03:36 ERROR Exception
Exception: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
Source: mscorlib
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj)
   at Sitecore.Jobs.JobRunner.RunMethod(JobArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Jobs.Job.ThreadEntry(Object state)

Nested Exception

Exception: System.InvalidOperationException
Message: Could not find configuration node: databases/database[@id='']
Source: Sitecore.Client
   at Sitecore.Shell.Applications.Install.Dialogs.BuildPackage.AsyncHelper.Generate()
   at Sitecore.Jobs.AsyncUI.JobMonitor.TaskRunner.Run()`
```

Anyone know what would cause this?  Seems it doesn't know what database to get the content out of.

I've created packages on this instance previously and it worked fine.  In fact, the previous package I created is still there, and I can generate a zip from that one fine.

This new package was created by loading that previous package, making some changes (it's using dynamic content), then saving and trying to generate zip.

Any suggestions?

**Comment by jeeby** [comment]
Sorry... creating the package from scratch resolved that issue.  Still interested to know why it happened, but not sure it's related to Habitat - probably more a Sitecore issue.

**Comment by mklimmasch** [comment]
Under certain circumstances, Sitecore seems to generate an empty entry, meaning the fields _Database_ and _Root_ are empty in the package XML. Easiest fix I found was to remove this entry and add it back in through the package manager.

Version 8.2.5
