### ISSUE TITLE
Publish Project task seems to doesn't work

### ISSUE THREAD

**Issue by lskowronski** [Sitecore/Habitat#376]
https://github.com/Sitecore/Habitat/blob/19b2bf9c1fbe1b12bea529a4a3489275eb53fc25/gulpfile.js#L220

When I try to run this with Visual Studio 2015 & Task Runner Explorer - i've got error message.
```

Error: 
------
 USAGE: -m Layer/Module 
------
    at formatError (C:\Development\Adecco\modis\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Development\Adecco\modis\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:116:13)
    at Gulp.emit (events.js:211:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Development\Adecco\modis\node_modules\orchestrator\index.js:264:8)
    at C:\Development\Adecco\modis\node_modules\orchestrator\index.js:275:23
    at finish (C:\Development\Adecco\modis\node_modules\orchestrator\lib\runTask.js:21:8)
    at module.exports (C:\Development\Adecco\modis\node_modules\orchestrator\lib\runTask.js:36:10)
    at Gulp.Orchestrator._runTask (C:\Development\Adecco\modis\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Development\Adecco\modis\node_modules\orchestrator\index.js:214:10)
Process terminated with code 1.
```

**Comment by rk92269** [comment]
Any solution on this ?

**Comment by faiyazulnoor** [comment]
I tried with VS 2017 and didn't face any such issue.

**Comment by nickwesselman** [comment]
@lskowronski This target is used to publish specific modules, rather than all at once. You can use it from the command line like so:

```
PS C:\dev\Habitat> gulp Publish-Project -m Feature/Accounts
```

To publish all projects, use the `Publish-All-Projects` task.

Going forward, for support questions, please use [Sitecore Stackexchange](https://sitecore.stackexchange.com) or #helix-habitat on [Sitecore Community Slack](https://www.akshaysura.com/2015/10/27/how-to-join-sitecore-slack-community-chat/). This repository's issues are reserved for feature requests and bug reports. Thanks!
