### ISSUE TITLE
Functional / exploratory testing on v9

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/Habitat#387]
Would be good to get a few folks going through this:

- [x] Install
- [x] All content pages
- [x] Experience editor
- [x] Register / login
- [x] Facebook login
- [x] Profiling / goals / Demo module
- [x] Search
- [x] Language switch
- [x] Uninstall

Testing can be done by pulling down the `feature/v9` branch, running `install-xp0.ps1` to install Sitecore (place needed files in `build\assets`) and then `gulp` to deploy Habitat.

**Comment by jeanfrancoislarente** [comment]
Just spent a few minutes going through a fresh install + some tests:

- **Install** - PR #413 would help some edge cases (already merged - thanks!)
- **All Content pages** - Browsed site, looks good with no blaring issues
- **Experience Editor** - Switched back & forth, can't see any issues
- **Register / Login** - no issues
- **Facebook Login** - not tested
- **Profiling / goals / Demo Module** - errors in log and in sidebar - see end of comment
- **Search** - Had to re-index (not in instructions) but search worked as expected after that (including typeahead search)
- **Language switching** - works - except as reported in #411 
- **Uninstall** - worked perfectly

**Profiling/Goals error**
Registered a new user. noticed the Login and Register goals were triggered. When looking at page events I see "Error" in the Name column. Looks like it _may_ be related to:

32152 12:49:18 ERROR Application error.
Exception: System.Web.HttpUnhandledException
Message: An unhandled exception occurred.
Source: Sitecore.Mvc
   at Nested Exception

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: App_Web__experiencedatacontent.cshtml.646c8dae.qkrqyx88
   at ASP._Page_Views_Demo__ExperienceDataContent_cshtml.Execute() in C:\inetpub\wwwroot\habitat.dev.local\Views\Demo\_ExperienceDataContent.cshtml:line 5
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)...

**Comment by nickwesselman** [comment]
Thanks JFL. I can't repro the "Error" in the Demo sidebar, if anyone else sees it, please let me know. I did repro that stacktrace when attempting to Refresh or End Visit in the sidebar (#417).
