### ISSUE TITLE
NullReferenceException when attempting to End Visit

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/Habitat#417]
Attempting to use the End Visit functionality in the Demo sidebar results in the following error in the logs:

```
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: App_Web__experiencedatacontent.cshtml.646c8dae.m46lxz7k
   at ASP._Page_Views_Demo__ExperienceDataContent_cshtml.Execute() in C:\inetpub\wwwroot\habitat.dev.local\Views\Demo\_E
xperienceDataContent.cshtml:line 5
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderi
ngBase startPage)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, Resul
tExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, Resul
tExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, Resul
tExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, Resul
tExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1
filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncR
esult)
```

Though it does seem to end the visit.

**Comment by nickwesselman** [comment]
Refresh seems to trigger the same error.
